CREATE SCHEMA IF NOT EXISTS orderservice;

SET search_path TO orderservice, public;

GRANT ALL PRIVILEGES ON SCHEMA orderservice TO katusha;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA orderservice TO katusha;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA orderservice TO katusha;

ALTER DEFAULT PRIVILEGES IN SCHEMA orderservice GRANT ALL ON TABLES TO katusha;
ALTER DEFAULT PRIVILEGES IN SCHEMA orderservice GRANT ALL ON SEQUENCES TO katusha;