CREATE SCHEMA IF NOT EXISTS userservice;

SET search_path TO userservice, public;

GRANT ALL PRIVILEGES ON SCHEMA userservice TO katusha;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA userservice TO katusha;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA userservice TO katusha;

ALTER DEFAULT PRIVILEGES IN SCHEMA userservice GRANT ALL ON TABLES TO katusha;
ALTER DEFAULT PRIVILEGES IN SCHEMA userservice GRANT ALL ON SEQUENCES TO katusha;