CREATE SCHEMA IF NOT EXISTS authservice;

SET search_path TO authservice, public;

GRANT ALL PRIVILEGES ON SCHEMA authservice TO katusha;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA authservice TO katusha;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA authservice TO katusha;

ALTER DEFAULT PRIVILEGES IN SCHEMA authservice GRANT ALL ON TABLES TO katusha;
ALTER DEFAULT PRIVILEGES IN SCHEMA authservice GRANT ALL ON SEQUENCES TO katusha;