spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:katusha}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:katusha}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=userservice

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=${SPRING_LIQUIBASE_ENABLED:true}
spring.liquibase.default-schema=userservice

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false

logging.level.by.rublevskaya.userservice=${LOGGING_LEVEL_BY_RUBLEVSKAYA_USERSERVICE:INFO}
logging.level.org.springframework.cache=INFO

springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.openapi.dev-url=${SPRINGDOC_OPENAPI_DEV_URL:http://localhost:8080}

postgres.db=${POSTGRES_DB:postgres}
postgres.user=${POSTGRES_USER:katusha}
postgres.password=${POSTGRES_PASSWORD:katusha}
postgres.host.port=${POSTGRES_HOST_PORT:5433}
redis.host.port=${REDIS_HOST_PORT:6380}
application.host.port=${APPLICATION_HOST_PORT:8080}

jwt.secret=${JWT_SECRET:231962b41fccd0163cb87032579b0185}
server.port=${APPLICATION_PORT:8081}