server.port=8082

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://auth-postgres:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:katusha}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:katusha}

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.liquibase.enabled=${SPRING_LIQUIBASE_ENABLED:true}

jwt.secret=${JWT_SECRET:MySecretKeyForJWTTokenGenerationThatIsLongEnoughForHS256Algorithm}
jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION:900000}
jwt.refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION:86400000}

logging.level.by.rublevskaya.authservice=${LOGGING_LEVEL:INFO}

springdoc.openapi.dev-url=${SPRINGDOC_OPENAPI_DEV_URL:http://localhost:8081}