spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:katusha}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:katusha}

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.default_schema=orderservice

spring.liquibase.enabled=${SPRING_LIQUIBASE_ENABLED:true}
spring.liquibase.default-schema=orderservice

logging.level.by.rublevskaya.orderservice=${LOGGING_LEVEL_BY_RUBLEVSKAYA_ORDERSERVICE:INFO}
logging.level.org.springframework.cache=INFO

springdoc.openapi.dev-url=${SPRINGDOC_OPENAPI_DEV_URL:http://localhost:8080}

postgres.db=${POSTGRES_DB:postgres}
postgres.user=${POSTGRES_USER:katusha}
postgres.password=${POSTGRES_PASSWORD:katusha}
postgres.host.port=${POSTGRES_HOST_PORT:5433}
redis.host.port=${REDIS_HOST_PORT:6380}
application.host.port=${APPLICATION_HOST_PORT:8080}