spring.profiles.active=@activatedProperties@
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=orderservice

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yml
spring.liquibase.default-schema=orderservice

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.try-it-out-enabled=true

user-service.base-url=http://127.0.0.1:8081
jwt.secret=231962b41fccd0163cb87032579b0185

resilience4j.circuitbreaker.instances.userService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userService.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.userService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.userService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.userService.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.userService.permittedNumberOfCallsInHalfOpenState=3

resilience4j.timelimiter.instances.userService.timeoutDuration=2s

spring.main.web-application-type=servlet

